[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

# if you choose `ruff` itself
[language-server.ruff]
command = "ruff"
args = ["server"]

#angular config
[language-server.angular-ls]
command = "ngserver"

args = [
  "--ngProbeLocations",
  "${$NODE_MODULES_GLOBAL}",
  "--tsProbeLocations",
  "${$NODE_MODULES_GLOBAL}",
  "--stdio",
  # If this for some reason doesn't work, try replacing ${NODE_MODULES_GLOBAL} with the absolute paths, e.g. output of `npm root -g`
]


file-types = ["ts", "typescript", "html"]

[[language]]
name = "typescript"
language-servers = ["angular-ls", "typescript-language-server"]

[[language]]
name = "html"
language-servers = ["angular-ls", "vscode-html-language-server"]
